### ISSUE TITLE
About TSNE result

### ISSUE THREAD

**Issue by xiaoli1996** [kaen2891/stethoscope-guided_supervised_contrastive_learning#1]
Where can I find the codes for your paper about TSNE results? Thanks

**Comment by kaen2891** [comment]
Hello @xiaoli1996 

I'm sorry to tell you that I'm very busy with other things. 

So could you please give me a week or so? 

I'll provide the README and the rest of the code in the meantime.

**Comment by xiaoli1996** [comment]
I completely understand how busy things can get. I appreciate your willingness to provide the README and the remaining code.

**Comment by kaen2891** [comment]
Hi @xiaoli1996 
We added the TSNE codes.
Sorry for the late work done.

**Comment by xiaoli1996** [comment]
Thank you very much!
