### ISSUE TITLE
스크립트 실행 시 마다 동일한 결과

### ISSUE THREAD

**Issue by dosorida** [kaen2891/stethoscope-guided_supervised_contrastive_learning#3]
git clone해서 코드 실행시켰는데 스크립트를 반복 실행해도 매번 동일한 결과가 나옵니다.

예를 들어
첫 번째 실행:
Train epoch 15, total time 147.96, accuracy:91.35
 * S_p: 58.71, S_e: 50.04, Score: 54.38 (Best S_p: 72.01, S_e: 48.00, Score: 60.01)
 * Acc@1 55.01
두 번째 실행:
 Train epoch 15, total time 147.88, accuracy:91.35
 * S_p: 58.71, S_e: 50.04, Score: 54.38 (Best S_p: 72.01, S_e: 48.00, Score: 60.01)
 * Acc@1 55.01

이런 식으로 score와 accuracy가 항상 동일하게 나오는데 혹시 이러는 이유를 알 수 있을까요?

**Comment by kaen2891** [comment]
재현성 때문에 동일한 결과가 나오는게 당연합니다. seed 를 변경해줘야 하는데요, `SEED="1 2 3 4 5"` 가 맞는지 확인 부탁드립니다.

**Comment by dosorida** [comment]
앗 확인이 늦었네요 해결되었습니다 감사합니다!
